generatorName: typescript-axios
inputSpec: https://www.keycloak.org/docs-api/latest/rest-api/openapi.json
outputDir: ./generated/api/keycloak
additionalProperties:
  supportsES6: true
  useSingleRequestParameter: true
#openapiNormalizer:
#  FILTER: "tag:Users"
